# \u6570\u636E\u6E90
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/club_manage?serverTimezone=GMT%2B8&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: xqx1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# \u65E5\u5FD7\u914D\u7F6E\uFF08\u5F00\u53D1\u7528\uFF09
logging:
  level:
    com:
      xwork: DEBUG
# \u670D\u52A1\u7AEF\u53E3
server:
  port: 5188

system:
  default-password: 1234  # \u9ED8\u8BA4\u5BC6\u7801
  upload-path: e:/expense-manage/upload
#  upload-path: /Users/longder/expense-manage/upload

